In [2]:
import joblib
import pandas as pd
from sklearn.metrics import accuracy_score

In [4]:
loaded_model = joblib.load('../dump/random_forest_model.pkl')

In [7]:

# Load the new data
new_data = pd.read_csv('../data/price_2.csv') 

# Grab the new features
new_features = new_data[['RSI', 'k_percent', 'r_percent', 'Price_Rate_Of_Change', 'MACD', 'On Balance Volume']] 

# Make a prediction
new_data['Model_Prediction'] = loaded_model.predict(new_features)

# Print the first 50 rows
print(new_data[['datetime', 'symbol', 'Close', 'Prediction', 'Model_Prediction']].head(50))

      datetime symbol       Close  Prediction  Model_Prediction
0   2023-01-23    AMD   76.529999         1.0               1.0
1   2023-01-24    AMD   74.699997        -1.0               1.0
2   2023-01-25    AMD   74.910004         1.0               1.0
3   2023-01-26    AMD   75.160004         1.0               1.0
4   2023-01-27    AMD   75.400002         1.0               1.0
5   2023-01-30    AMD   72.449997        -1.0               1.0
6   2023-01-31    AMD   75.150002         1.0               1.0
7   2023-02-01    AMD   84.639999         1.0               1.0
8   2023-02-02    AMD   88.309998         1.0               1.0
9   2023-02-03    AMD   86.089996        -1.0              -1.0
10  2023-02-06    AMD   83.680000        -1.0              -1.0
11  2023-02-07    AMD   85.910004         1.0               1.0
12  2023-02-08    AMD   84.690002        -1.0              -1.0
13  2023-02-09    AMD   83.209999        -1.0              -1.0
14  2023-02-10    AMD   81.480003        -1.0              -1.0
15  2023-02-13    AMD   83.129997         1.0               1.0
16  2023-02-14    AMD   85.949997         1.0               1.0
17  2023-02-15    AMD   85.180000        -1.0              -1.0
18  2023-02-16    AMD   80.080002        -1.0              -1.0
19  2023-02-17    AMD   78.500000        -1.0              -1.0
20  2023-02-21    AMD   76.769997        -1.0              -1.0
21  2023-02-22    AMD   76.610001        -1.0              -1.0
22  2023-02-23    AMD   79.750000         1.0               1.0
23  2023-02-24    AMD   78.089996        -1.0              -1.0
24  2023-02-27    AMD   78.769997         1.0               1.0
25  2023-02-28    AMD   78.580002        -1.0              -1.0
26  2023-03-01    AMD   78.290001        -1.0              -1.0
27  2023-03-02    AMD   80.440002         1.0               1.0
28  2023-03-03    AMD   81.519997         1.0               1.0
29  2023-03-06    AMD   81.160004        -1.0              -1.0
30  2023-03-07    AMD   82.110001         1.0               1.0
31  2023-03-08    AMD   85.370003         1.0               1.0
32  2023-03-09    AMD   84.029999        -1.0              -1.0
33  2023-03-10    AMD   82.669998        -1.0              -1.0
34  2023-03-13    AMD   82.010002        -1.0              -1.0
35  2023-03-14    AMD   87.449997         1.0               1.0
36  2023-03-15    AMD   89.680000         1.0               1.0
37  2023-03-16    AMD   96.599998         1.0               1.0
38  2023-03-17    AMD   97.839996         1.0               1.0
39  2023-03-20    AMD   96.809998        -1.0              -1.0
40  2023-03-21    AMD   95.930000        -1.0              -1.0
41  2023-03-22    AMD   97.580002         1.0               1.0
42  2023-03-23    AMD  100.279999         1.0               1.0
43  2023-03-24    AMD   97.949997        -1.0              -1.0
44  2023-03-27    AMD   96.610001        -1.0              -1.0
45  2023-03-28    AMD   94.559998        -1.0              -1.0
46  2023-03-29    AMD   96.089996         1.0               1.0
47  2023-03-30    AMD   97.879997         1.0               1.0
48  2023-03-31    AMD   98.010002         1.0               1.0
49  2023-04-03    AMD   96.559998        -1.0              -1.0

In [11]:
# Calculate the accuracy
accuracy = accuracy_score(new_data['Prediction'], new_data['Model_Prediction'])
print('Accuracy: {} %'.format(accuracy*100))

Accuracy: 65.79520697167756 %

In [24]:
def execute_trade():
    # Grab the last row of the data frame
    # Filter the DataFrame to include rows with the latest date and ticker symbol
    last_row = new_data[(new_data['datetime'] == new_data['datetime'].max())]

    # Print the filtered row
    # return last_row.head()
    
    
    print("Signals for today are: ")
    for index, row in last_row.iterrows():
        print(row['symbol']," : ", row['Model_Prediction'])
    
    print("\nExecuting the following trades: ")
    #If the prediction is 1, then buy
    for index, row in last_row.iterrows():
        if row['Model_Prediction'] == 1:
            print('Buying', row['symbol'])
        else:
            print('Selling',row['symbol'])
    
    print("\n")
    print("The detailed information for the trades as follows :")
    return last_row.head()
execute_trade()

Signals for today are:
AMD  :  -1.0
GOOG  :  -1.0
META  :  1.0

Executing the following trades:
Selling AMD
Selling GOOG
Buying META


The detailed information for the trades as follows :

,Unnamed: 0,datetime,symbol,Open,High,Low,Close,Volume,Dividends,Stock Splits,...,low_14,high_14,k_percent,r_percent,MACD,MACD_EMA,Price_Rate_Of_Change,On Balance Volume,Prediction,Model_Prediction
305,637,2024-04-10,AMD,166.710007,169.779999,164.000000,167.139999,59600000.0,0.0,0.0,...,164.000000,187.690002,13.254534,-86.745466,-4.124253,-2.241646,-0.069325,2.128422e+09,-1.0,-1.0
611,318,2024-04-10,GOOG,157.880005,158.160004,156.199997,157.660004,16339200.0,0.0,0.0,...,148.009995,159.889999,81.229000,-18.771000,3.708026,3.226405,0.037646,6.753161e+08,-1.0,-1.0
917,956,2024-04-10,META,509.290009,522.559998,505.799988,519.830017,11418500.0,0.0,0.0,...,481.779999,531.489990,76.544005,-23.455995,10.252148,9.659068,0.052586,8.435758e+08,1.0,1.0